- type: department
  id: Militech
  name: Корпорация Militech
  description: department-Militech-description
  color: "#2e4053"
  roles:
    - HoSMilitech
    - HoDMilitech
    - SquadCommanderMilitech
    - SecurityMilitech
    - MedTechM
    - OperativeMilitech

- type: department
  id: NCPD
  name: NCPD
  description: department-NCPD-description
  color: "#1e90ff"
  roles:
    - NCPDChief
    - NCPDOfficer
    - NCPDSWAT
    - NCPDInspector

- type: department
  id: TraumaTeam
  name: Отдление TraumaTeam
  description: department-TraumaTeam-description
  color: "#e74c3c"
  roles:
    - TraumaTeamChief
    - TraumaTeamDoctor
    - TraumaTeamChemist
    - TraumaTeamParamedic
    - TraumaTeamOperative
