using Content.Shared._NC.Trauma;
using Content.Client.UserInterface.Controls; // Здесь живет FancyWindow
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths; // Для Thickness

namespace Content.Client._NC.Trauma
{
    [GenerateTypedNameReferences]
    public sealed partial class TraumaComputerWindow : FancyWindow 
    {
        public event Action<NetEntity, TraumaSubscriptionTier>? OnSubscriptionChanged;

        public TraumaComputerWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void UpdateState(TraumaComputerState state)
        {
            PatientList.DisposeAllChildren();

            foreach (var patient in state.Patients)
            {
                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    MinHeight = 40,
                    Margin = new Thickness(0, 5)
                };

                row.AddChild(new Label 
                { 
                    Text = patient.Name, 
                    HorizontalExpand = true,
                    ClipText = true
                });
                
                var healthLabel = new Label { Text = patient.HealthStatus, MinWidth = 100 };
                
                if (patient.HealthStatus == "Dead") healthLabel.Modulate = Color.Red;
                else if (patient.HealthStatus == "Critical") healthLabel.Modulate = Color.Orange;
                else healthLabel.Modulate = Color.Green;
                
                row.AddChild(healthLabel);

                var tierSelector = new OptionButton { MinWidth = 120 };
                
                for (int i = 0; i <= 4; i++)
                {
                    var tier = (TraumaSubscriptionTier)i;
                    tierSelector.AddItem(tier.ToString(), i);
                    
                    if (tier == patient.Subscription) 
                        tierSelector.Select(i);
                }

                tierSelector.OnItemSelected += args =>
                {
                    tierSelector.SelectId(args.Id);
                    var newTier = (TraumaSubscriptionTier)args.Id;
                    OnSubscriptionChanged?.Invoke(patient.EntityUid, newTier);
                };

                row.AddChild(tierSelector);
                PatientList.AddChild(row);
            }
        }
    }
}